stages:
  - build
  - test
  - docker
  - deploy

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

build:
  stage: build
  image: node:18-alpine
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  image: node:18-alpine
  script:
    - npm test

docker:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  before_script:
    - echo "$KUBE_CONFIG" | base64 -d > ~/.kube/config
    - kubectl config use-context my-kube-context
  script:
    - helm upgrade --install ip-reverse-app ./helm --set image.repository=$CI_REGISTRY_IMAGE --set image.tag=$CI_COMMIT_SHA